### ISSUE TITLE
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

### ISSUE THREAD

**Issue by w3lifer** [Vonage/vonage-php-sdk#2]
The following warning appears when installing your package:

> Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

**Comment by lornajane** [comment]
Thanks for raising this! We've got a pull request open already so this change will be in one of our upcoming releases, if you'd like to keep an eye on it, you can follow along here: https://github.com/Nexmo/nexmo-php/pull/207

**Comment by dragonmantank** [comment]
This should be corrected as of v2.2.0! Thanks!
