### ISSUE TITLE
SMS sending freezes the execution if throttle occurs

### ISSUE THREAD

**Issue by codewahoo** [Vonage/vonage-php-sdk#6]
Line 51 in src/SMS/Client.php calls PHP sleep function, which expects a timeout in seconds, whereas src/SMS/ExceptionErrorHandler.php throws a ThrottleException object with a timeout in milliseconds.
Thus, the script freezes for xxx seconds instead of milliseconds.

**Comment by lemattou** [comment]
it's been a long time since this error is present, SOS

**Comment by SecondeJK** [comment]
This looks like an error in the core, not in this package which is the core plus Guzzle.
Could you please open an issue at https://github.com/Vonage/vonage-php-sdk-core
