### ISSUE TITLE
Wrong Unicode detection

### ISSUE THREAD

**Issue by pfx2** [Vonage/vonage-php-sdk#9]
When sending SMS in text mode, sometimes messages are wrongly detected as Unicode, and a warning error is triggered.

Step to reproduce :

1) Try to send the following message with the SDK  : Pensez à votre rendez-vous demain à la pharmacie
2) Message will be detected as Unicode, and a warning error will be triggered.

It is because of the "isUnicode" method, that returns true because of the "à" character, which is a valid GSM character.

**Comment by SecondeJK** [comment]
You are using an old version of the SDK that contained numerous bugs when trying to work with Unicode detection.
Please upgrade `vonage/client-core` to the latest version.

You need to now use the following static method:
`namespace Vonage\SMS\Message\SMS::isGsm7()`
